services:
  frontend:
    container_name: frontend
    image: frontend:v1.0.0
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapping port 3000 from container to host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for file change detection in certain environments (Docker for Mac/Windows)
    volumes:
      - ./frontend/src:/app/src  # Bind mount the 'src' folder so changes are reflected
    command: npm run dev
    working_dir: /app # Ensures we're in the app directory
  
  backend:
    container_name: backend
    image: backend:v1.0.0
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: usr_mgt
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: usr_mgt
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
