version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount local frontend directory to container
    environment:
      - NODE_ENV=development
    command: npm run dev
  
#   backend:
#     build: ./backend
#     ports:
#       - "3001:3001"
#     volumes:
#       - ./backend:/app
#     environment:
#       - NODE_ENV=development
#       - DB_HOST=db
#       - DB_PORT=3306
#       - DB_USER=root
#       - DB_PASSWORD=secret
#       - DB_NAME=usr_mgt
#     depends_on:
#       - db
#     command: npm start

#   db:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: usr_mgt
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
